/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * 项目具体数据
 */
export interface Schema {
    /**
     * 项目编号
     */
    floor: number;
    /**
     * 项目名称
     */
    title: string;
    /**
     * 项目介绍
     */
    detail?: string;
    /**
     * 活动具体内容
     *
     * @minItems 1
     */
    stages: [
        {
            /**
             * 内容名称
             */
            name: string;
            /**
             * 活动时间
             *
             * 例如 2024 年 9 月 1 日到 2024 年 9 月 10 日，中间扣掉 9 月 3 日，即表示为
             * [[2024, 9, 1], [2024, 9, 2], [2024, 9, 4], [2024, 9, 10]]
             *
             * @minItems 1
             */
            timeStep: [number[], ...number[][]];
            /**
             * 活动的描述
             */
            detail?: string;
            [k: string]: unknown;
        },
        ...{
            /**
             * 内容名称
             */
            name: string;
            /**
             * 活动时间
             *
             * 例如 2024 年 9 月 1 日到 2024 年 9 月 10 日，中间扣掉 9 月 3 日，即表示为
             * [[2024, 9, 1], [2024, 9, 2], [2024, 9, 4], [2024, 9, 10]]
             *
             * @minItems 1
             */
            timeStep: [number[], ...number[][]];
            /**
             * 活动的描述
             */
            detail?: string;
            [k: string]: unknown;
        }[]
    ];
    [k: string]: unknown;
}
